-- Criar tabela client_team_history
CREATE TABLE IF NOT EXISTS client_team_history (
  id UUID PRIMARY KEY,
  client_id UUID NOT NULL,
  old_team VARCHAR(255),
  new_team VARCHAR(255),
  changed_by UUID,
  changed_at TIMESTAMP WITH TIME ZONE,
  motivo TEXT
);

-- Criar tabela clients com todas as colunas
CREATE TABLE IF NOT EXISTS clients (
  id UUID PRIMARY KEY,
  report_id UUID,
  user_id UUID,
  client_id VARCHAR(255),
  name VARCHAR(500),
  mix_de_produtos VARCHAR(255),
  valor DECIMAL(15,2),
  rk INTEGER,
  created_at TIMESTAMP WITH TIME ZONE,
  company_name VARCHAR(500),
  cnpj VARCHAR(20),
  contact_name VARCHAR(500),
  phone VARCHAR(20),
  person_type VARCHAR(50),
  razao_social VARCHAR(500),
  nome_fantasia VARCHAR(500),
  cpf VARCHAR(15),
  rg VARCHAR(20),
  cep VARCHAR(10),
  endereco VARCHAR(500),
  cidade VARCHAR(255),
  estado VARCHAR(2),
  bairro VARCHAR(255),
  address_sub_region VARCHAR(255),
  email VARCHAR(255),
  client_type VARCHAR(100),
  business_group VARCHAR(255),
  payment_form VARCHAR(100),
  price_list VARCHAR(100),
  credit_limit DECIMAL(15,2),
  credit_docs_quantity INTEGER,
  credit_validity VARCHAR(50),
  credit_status VARCHAR(50),
  average_term_days INTEGER,
  cost_center VARCHAR(100),
  accounting_account VARCHAR(100),
  team VARCHAR(255),
  representatives TEXT,
  observations TEXT,
  alerts TEXT,
  tax_regime VARCHAR(100),
  calculates_icms BOOLEAN,
  sale_with_ipi BOOLEAN,
  ipi_in_icms_base BOOLEAN,
  exempt_icms BOOLEAN,
  icms_reduction_percentage DECIMAL(5,2),
  icms_st_reduction_percentage DECIMAL(5,2),
  st_rate_percentage DECIMAL(5,2),
  tax_substitution BOOLEAN,
  icms_deferral BOOLEAN,
  final_consumer BOOLEAN,
  presence_indicator VARCHAR(50),
  suframa_inscription VARCHAR(100),
  grant_suframa_discount BOOLEAN,
  state_inscriptions TEXT,
  legal_basis VARCHAR(255),
  operation_nature VARCHAR(255),
  service_taxation VARCHAR(100),
  pix_key VARCHAR(255),
  bank_number VARCHAR(10),
  bank_agency VARCHAR(10),
  bank_account VARCHAR(20),
  account_holder VARCHAR(255),
  add_delivery_fee_to_bill BOOLEAN,
  not_protest_delivery_bill BOOLEAN,
  automatic_invoice BOOLEAN,
  daily_interest_percentage DECIMAL(5,2),
  fine_percentage DECIMAL(5,2),
  hide_installment_on_bill BOOLEAN,
  freight_knowledge VARCHAR(100),
  preferred_carrier VARCHAR(255),
  freight_preselection VARCHAR(100),
  nf_transfer_path VARCHAR(500),
  situacao_cadastral VARCHAR(100),
  capital_social DECIMAL(15,2),
  inscricao_municipal VARCHAR(50),
  site VARCHAR(255),
  contatos TEXT,
  price_table_id VARCHAR(100),
  curve_class VARCHAR(50),
  address VARCHAR(500),
  cotacao_moeda VARCHAR(10),
  inscricao_estadual VARCHAR(50),
  ipi_na_bc_icms BOOLEAN,
  lote_produto VARCHAR(100),
  nao_participar_controle_premiacao BOOLEAN,
  somar_taxa_entrega_boleto BOOLEAN,
  tipo_cliente VARCHAR(100),
  vencimento_minimo INTEGER,
  nome_equipe VARCHAR(255),
  user_name VARCHAR(255),
  opening_date DATE,
  company_size VARCHAR(100),
  registration_status_date DATE,
  is_active BOOLEAN,
  last_contact_date DATE,
  potential_level VARCHAR(50),
  address_region VARCHAR(255),
  CNAE VARCHAR(20),
  "CNAE-Principal" VARCHAR(255),
  data_consulta DATE,
  data_abertura DATE,
  potential_level_int INTEGER,
  potencial_compra VARCHAR(50),
  potencial_score DECIMAL(5,2),
  converted_from_lead_id UUID,
  conversion_date DATE,
  ultima_compra DATE,
  valor_backup DECIMAL(15,2)
);

-- Criar índices para melhor performance
CREATE INDEX IF NOT EXISTS idx_client_team_history_client_id ON client_team_history(client_id);
CREATE INDEX IF NOT EXISTS idx_client_team_history_changed_at ON client_team_history(changed_at);
CREATE INDEX IF NOT EXISTS idx_clients_cnpj ON clients(cnpj);
CREATE INDEX IF NOT EXISTS idx_clients_email ON clients(email);
CREATE INDEX IF NOT EXISTS idx_clients_city ON clients(cidade);
CREATE INDEX IF NOT EXISTS idx_clients_team ON clients(team);
CREATE INDEX IF NOT EXISTS idx_clients_is_active ON clients(is_active);
