CREATE TABLE `contas_receber` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cont` varchar(20) NOT NULL,
	`situacao` varchar(10),
	`provisao` varchar(20),
	`num_nf` varchar(20),
	`cod_pessoa` varchar(20),
	`parcela` varchar(10) NOT NULL,
	`num_ecf_serie_nf` varchar(20),
	`dta_transf_borderaux` varchar(20),
	`ctrl_varios_docs` varchar(20),
	`dta_vecto` date,
	`valor` decimal(15,2) DEFAULT '0',
	`dta_pagto` date,
	`valor_pago` decimal(15,2) DEFAULT '0',
	`tipo_doc` varchar(10),
	`desc_desconto` varchar(100),
	`desconto` decimal(15,2) DEFAULT '0',
	`desc_valor` varchar(20),
	`dta_emissao` date,
	`tipo_pagto` varchar(10),
	`obs` text,
	`sit_doc` varchar(10),
	`regiao` varchar(50),
	`razao_cli` varchar(255),
	`cidade` varchar(100),
	`descricao` varchar(100),
	`razao` varchar(255),
	`vendedor` varchar(255),
	`cod_equipe` varchar(20),
	`cod_empresa` varchar(10) NOT NULL,
	`documento` varchar(20),
	`apelido_emp` varchar(50),
	`atraso_dias` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `contas_receber_id` PRIMARY KEY(`id`),
	CONSTRAINT `uq_cont_parcela_empresa` UNIQUE(`cont`,`parcela`,`cod_empresa`)
);
