/**
 * Mapeamento de cidades para UF (estado) baseado nos dados do banco.
 * Quando a cidade não é encontrada, retorna "N/D".
 */
const CIDADE_UF: Record<string, string> = {
  "ALTA FLORESTA": "MT",
  "ALTO BELA VISTA": "SC",
  "ANDRADINA": "SP",
  "APARECIDA DO TABOADO": "MS",
  "ARAGOIANIA": "GO",
  "ARAGUARI": "MG",
  "ARAXA": "MG",
  "AUGUSTINOPOLIS": "TO",
  "AUTAZES": "AM",
  "BALSA NOVA": "PR",
  "BARRETOS": "SP",
  "BIGUAÇU": "SC",
  "BITURUNA": "PR",
  "BODOCO": "PE",
  "BRAÇO DO NORTE": "SC",
  "BRASILIA": "DF",
  "BRUMADINHO": "MG",
  "BURI": "SP",
  "CAARAPO": "MS",
  "CAJURU": "SP",
  "CALDAS NOVAS": "GO",
  "CAMPO LIMPO DE GOIAS": "GO",
  "CAMPO MAGRO": "PR",
  "CANDIDO DE ABREU": "PR",
  "CARMO DO PARANAIBA": "MG",
  "CASCA": "RS",
  "CASTRO": "PR",
  "CATANDUVA": "SP",
  "CHAPADAO DO SUL": "MS",
  "COMENDADOR LEVY GASPARIAN": "RJ",
  "COMODORO": "MT",
  "COROMANDEL": "MG",
  "CORONEL VIVIDA": "PR",
  "CRIXAS": "GO",
  "CRUZEIRO DA FORTALEZA": "MG",
  "CURITIBA": "PR",
  "DOURADOS": "MS",
  "DOUTOR CAMARGO": "PR",
  "EMILIANOPOLIS": "SP",
  "ESTRELA D OESTE": "SP",
  "FAZENDA RIO GRANDE": "PR",
  "FLORESTAL": "MG",
  "FLORIANOPOLIS": "SC",
  "FORMOSA DO OESTE": "PR",
  "FORTALEZA": "CE",
  "FOZ DO IGUAÇU": "PR",
  "GOIANIA": "GO",
  "GUARAÇAI": "SP",
  "GUARULHOS": "SP",
  "GUIMARANIA": "MG",
  "IBICUI": "BA",
  "IBITIRAMA": "ES",
  "IGUAI": "BA",
  "IMBITUVA": "PR",
  "INHAPIM": "MG",
  "IPORA": "GO",
  "IRETAMA": "PR",
  "ITAJU": "SP",
  "ITANHOMI": "MG",
  "ITAPETININGA": "SP",
  "ITAPUI": "SP",
  "ITARANTIM": "BA",
  "ITIUBA": "BA",
  "IVATE": "PR",
  "IVINHEMA": "MS",
  "IVOTI": "RS",
  "JABOTICABAL": "SP",
  "JALES": "SP",
  "JAU": "SP",
  "LAGOA DOS PATOS": "MG",
  "LARANJEIRAS DO SUL": "PR",
  "LIMA DUARTE": "MG",
  "LUMINARIAS": "MG",
  "LUZIANIA": "GO",
  "MAGE": "RJ",
  "MALACACHETA": "MG",
  "MANAUS": "AM",
  "MATUTINA": "MG",
  "MOGI GUAÇU": "SP",
  "MONTE ALEGRE DE GOIAS": "GO",
  "MOSSORO": "RN",
  "MUNHOZ DE MELO": "PR",
  "NAZARENO": "MG",
  "NITEROI": "RJ",
  "NOVA ALIANCA": "SP",
  "NOVA ALIANCA DO IVAI": "PR",
  "NOVA CANAA": "BA",
  "NOVO HORIZONTE": "SP",
  "OLIMPIA": "SP",
  "OLIMPIO NORONHA": "MG",
  "PACATUBA": "CE",
  "PALHOCA": "SC",
  "PALMAS DE MONTE ALTO": "BA",
  "PARACATU": "MG",
  "PARAISO": "SP",
  "PASSO FUNDO": "RS",
  "PASSOS": "MG",
  "PATOS DE MINAS": "MG",
  "PAULA FREITAS": "PR",
  "PAVAO": "MG",
  "PEROBAL": "PR",
  "PETROLANDIA": "SC",
  "PIRENOPOLIS": "GO",
  "PITANGA": "PR",
  "PLACAS": "PA",
  "POLONI": "SP",
  "POMPEU": "MG",
  "POTE": "MG",
  "PRESIDENTE FIGUEIREDO": "AM",
  "PRESIDENTE PRUDENTE": "SP",
  "PROFESSOR JAMIL": "GO",
  "PRUDENTOPOLIS": "PR",
  "RESENDE": "RJ",
  "RESERVA": "PR",
  "RIO BRANCO": "AC",
  "RIO DO SUL": "SC",
  "RIO PARANAIBA": "MG",
  "RIO POMBA": "MG",
  "RITAPOLIS": "MG",
  "ROMELANDIA": "SC",
  "RONDINHA": "RS",
  "SANTA CLARA D OESTE": "SP",
  "SAO BONIFACIO": "SC",
  "SAO CARLOS": "SP",
  "SAO FRANCISCO": "MG",
  "SAO FRANCISCO DE SALES": "MG",
  "SAO GERALDO": "MG",
  "SAO GONÇALO DO RIO ABAIXO": "MG",
  "SAO JOAO DA BOA VISTA": "SP",
  "SAO JORGE D OESTE": "PR",
  "SAO JOSE": "SC",
  "SAO JOSE DO RIO PRETO": "SP",
  "SAO JOSE DO SUL": "RS",
  "SAO JOSE DOS PINHAIS": "PR",
  "SAO LUIS DE MONTES BELOS": "GO",
  "SAO MARTINHO": "SC",
  "SAO PAULO": "SP",
  "SAO SEBASTIAO DA BELA VISTA": "MG",
  "SAO SEBASTIAO DA GRAMA": "SP",
  "SAO SEBASTIAO DO RIO VERDE": "MG",
  "SEBASTIANOPOLIS DO SUL": "SP",
  "SERRANOPOLIS DO IGUAÇU": "PR",
  "SOLEDADE": "RS",
  "TAIO": "SC",
  "TAQUARITINGA": "SP",
  "TENENTE PORTELA": "RS",
  "TRES PASSOS": "RS",
  "URUANA": "GO",
  "VARJAO DE MINAS": "MG",
  "VERE": "PR",
  "VITORIA DA CONQUISTA": "BA",
  "XINGUARA": "PA",
};

const UF_REGIAO: Record<string, string> = {
  AC: "Norte",
  AL: "Nordeste",
  AM: "Norte",
  AP: "Norte",
  BA: "Nordeste",
  CE: "Nordeste",
  DF: "Centro-Oeste",
  ES: "Sudeste",
  GO: "Centro-Oeste",
  MA: "Nordeste",
  MG: "Sudeste",
  MS: "Centro-Oeste",
  MT: "Centro-Oeste",
  PA: "Norte",
  PB: "Nordeste",
  PE: "Nordeste",
  PI: "Nordeste",
  PR: "Sul",
  RJ: "Sudeste",
  RN: "Nordeste",
  RO: "Norte",
  RR: "Norte",
  RS: "Sul",
  SC: "Sul",
  SE: "Nordeste",
  SP: "Sudeste",
  TO: "Norte",
};

const UF_NOME: Record<string, string> = {
  AC: "Acre",
  AL: "Alagoas",
  AM: "Amazonas",
  AP: "Amapá",
  BA: "Bahia",
  CE: "Ceará",
  DF: "Distrito Federal",
  ES: "Espírito Santo",
  GO: "Goiás",
  MA: "Maranhão",
  MG: "Minas Gerais",
  MS: "Mato Grosso do Sul",
  MT: "Mato Grosso",
  PA: "Pará",
  PB: "Paraíba",
  PE: "Pernambuco",
  PI: "Piauí",
  PR: "Paraná",
  RJ: "Rio de Janeiro",
  RN: "Rio Grande do Norte",
  RO: "Rondônia",
  RR: "Roraima",
  RS: "Rio Grande do Sul",
  SC: "Santa Catarina",
  SE: "Sergipe",
  SP: "São Paulo",
  TO: "Tocantins",
};

export function getUfFromCidade(cidade: string): string {
  if (!cidade) return "N/D";
  return CIDADE_UF[cidade.toUpperCase().trim()] || "N/D";
}

export function getRegiaoFromUf(uf: string): string {
  if (!uf || uf === "N/D") return "N/D";
  return UF_REGIAO[uf] || "N/D";
}

export function getEstadoNome(uf: string): string {
  if (!uf || uf === "N/D") return "Não identificado";
  return UF_NOME[uf] || uf;
}

export { CIDADE_UF, UF_REGIAO, UF_NOME };
